---
title: '프로미스'
date: 2025-04-09
desc: 자바스크립트의 프로미스에 대해 알아보자
cover: '/images/posts/JavaScript-DeepDive/modern-js.jpg'
---

## 비동기 처리를 위한 콜백 패턴의 단점

### 콜백 헬

예제의 get 함수는 서버의 응답 결과를 콘솔에 출력한다.

```jsx
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
```

get 함수는 비동기 함수이다. 비동기 함수란 함수 내부에서 비동기로 동작하는 코드를 포함한 함수를 말한다.

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않더라도 즉시 종료된다. <Highlighter>즉, 비동기 함수 내부의 비동기 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기 코드에서 처리 결과를 외부로 반환하려 하거나 상위 스코프의 변수로 할당하면 제대로 동작하지 않는다.</Highlighter>

예를들어, setTimeout도 비동기 함수이다. setTimeout을 호출하면 콜백 함수를 호출 스케줄링 한 후 종료된다. <Wavy>콜백 함수는 setTimeout이 종료된 이후 호출된다.</Wavy><br/>
위 예제의 get 함수도 비동기 함수이다. get 함수를 호출하면 GET 요청을 전송하고, onload 이벤트 핸들러를 등록한 다음 undefined를 반환하고 즉시 종료된다. <Wavy>비동기 함수인 get 함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후 실행된다.</Wavy>

<br />
get 함수가 서버의 응답 결과를 반환하도록 수정해보자.

```jsx {8}
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const response = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response); //undefined
```

get 함수는 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩 하고 종료한다. 이때 get 함수에는 명시적인 반환문이 없으므로 undefined를 반환한다.

xhr.load 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 get 함수의 반환문이 아니다. onload 이벤트 핸들러를 get 함수가 호출할 수 있다면 반환값을 캐치하여 다시 반환할 수 있겠지만 onload 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 반환값 또한 캐치할 수 없다.

<br />
만약 서버의 응답을 상위 스코프 변수에 할당하면 어떨까 ?

```jsx {10}
let todos;

const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1');
console.log(todos); //undefined
```

xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 언제나 `console.log(todos)`가 종료한 이후에 호출된다. 따라서 todos를 출력하는 시점에는 아직 todos 변수에 서버의 응답 결과가 할당되기 이전이다.

get 함수가 호출되면 get 함수의 실행 컨텍스트가 생성되고 콜 스택에 푸시된다. xhr.load 이벤트 핸들러가 바인딩되고 get 함수는 종료되며 콜 스택에서 팝된다. 이후 바로 console.log가 호출되어 콜 스택에 푸시된다. 서버로부터 응답이 도착하면 xhr 객체에서 load 이벤트가 발생한다. xhr.onload 이벤트 핸들러는 load 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, <Wavy>콜 스택이 비면</Wavy> 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

<Wavy>
  따라서 xhr.load 이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈 상태여야 하므로
  console.log는 이미 종료된 이후이다. 즉, 상위 스코프 변수 todos에 서버 응답을
  할당하기 이전에 console.log가 먼저 호출되어 undefined가 출력되는 것이다.
</Wavy>

이처럼 <Highlighter>비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프
변수에 할당할 수도 없다.</Highlighter>
비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이때 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다.

콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또 다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아진다. 이를 **콜백 헬**(callback hell)이라 한다.

서버로부터 응답을 취득하고, 이 데이터를 사용해 또 다시 get 요청을 하는 다음 사례는 콜백 헬이 발생하는 전형적인 사례이다.

```jsx
get('/step1', (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      get(`/step4/${c}`, (d) => {
        console.log(d);
      });
    });
  });
});
```

### 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중 하나는 에러 처리가 곤란하다는 것이다.

```jsx
try {
  setTimeout(() => {
    throw new Error('Error!');
  }, 1000);
} catch (e) {
  console.log('캐치한 에러', e);
}
```

위 예제의 setTimeout가 호출되면 콜 스택에 푸시되어 실행된다. setTimeout은 비동기 함수이므로 콜백 함수의 호출을 기다리지 않고 즉시 종료되어 팝된다. 타이머 만료 후 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

setTimeout의 콜백함수가 실행될 때 setTimeout은 이미 콜 스택에서 제거된 상태이다. <Wavy>에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래방향으로 전파된다.</Wavy> 하지만 setTimeout의 콜백함수를 호출한 것은 setTimeout이 아니고, 따라서 setTimeout의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

이처럼 비동기 처리를 위한 콜백 패턴은 콜백 헬이나 에러 처리가 곤란하다는 단점이 있다. 이를 극복하기 위해 프로미스가 도입되었다.

## 프로미스의 생성

Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스(Promise 객체)를 생성한다. Promise 생성자 함수는 비동기 처리를 위한 콜백 함수를 인수로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

```jsx
const promise = new Promise((resolve, reject) => {
	if(/* 비동기 처리 성공 */) {
		resolve('result');
	} else {
		reject('failure reason');
	}
});
```

Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리가 성공하면 resolve를, 실패하면 reject 함수를 호출한다.

프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지 나타내는 상태 정보를 갖는다.

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled            | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected             | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

실행된 직후의 프로미스는 기본적으로 pending 상태이다. 이후 비동기 처리가 수행되면 비동기 처리 결과에 따라 프로미스 상태가 변경된다. 이처럼 <Wavy>프로미스의 상태는 resolve 혹은 reject 함수를 호출하는 것으로 결정된다.</Wavy>

fulfilled 혹은 rejected 상태를 settled 상태라고 한다. settled 상태는 pending이 아닌 상태로 비동기 처리가 수행된 상태를 말한다. 프로미스는 pending 상태에서 fulfilled나 rejected의 settled 상태로 변화할 수 있으며, settled 상태가 되면 다른 상태로 변화할 수 없다.

또한 프로미스는 비동기 처리 상태와 더불어 비동기 처리 결과도 상태로 갖는다. 아래 예제를 보자.
![promise-value](/images/posts/JavaScript-DeepDive/promise-value.png)
비동기 처리가 성공하면 프로미스는 pending 상태에서 fulfilled 상태로 변화하며 비동기 처리 결과인 1을 값으로 갖는다.
비동기 처리가 실패하면 pending 상태에서 rejected로 변화하며 비동기 처리 결과인 Error를 값으로 갖는다.

즉, <Highlighter>프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체이다.</Highlighter>

## 프로미스의 후속 처리 메서드

프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 한다. 이를 위해 프로미스는 후속 메서드 then, catch, finally를 제공한다.

프로미스의 <Wavy>비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백
함수가 선택적으로 호출된다. </Wavy> 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다. 모든
후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작한다.

### Promise.prototype.then

then 메서드는 두 개의 콜백 함수를 인수로 전달받는다. 첫번째 콜백 함수는 비동기 처리가 성공했을때 호출되는 성공 처리 콜백 함수이며, 두번째 콜백 함수는 비동기 처리가 실패했을때 호출되는 실패 처리 콜백 함수다.

```jsx
new Promise((resolve) => resolve('fulfilled')).then(
  (v) => console.log(v),
  (e) => console.log(e)
);
```

then 메서드는 언제나 프로미스를 반환한다. then 메서드의 콜백 함수가 프로미스를 반환하면 그대로 반환, 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다.

### Promise.prototype.catch

catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다. catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우에만 호출된다.

```jsx
new Promise((_, reject) => reject(new Error('rejected'))).catch((e) =>
  console.log(e)
);
```

`.catch(e => console.log(e));` 는
`.then(undefined, e => console.log(e));`와 동일하게
동작한다. 또한 catch 메서드도 then 메서드와 마찬가지로 언제나 프로미스를
반환한다.

### Promise.prototype.finally

finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다. finally 메서드의 콜백 함수는 프로미스의 성공/실패 여부와 상관없이 무조건 한 번 호출되므로, 프로미스 상태와 관련 없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다. finally 메서드도 언제나 프로미스를 반환한다.

```jsx
new Promise(() => {}).finally(() => console.log('finally'));
```

## 프로미스의 에러 처리

위에서 살펴보았듯이 콜백 패턴은 에러 처리가 곤란하다는 문제가 있지만 프로미스는 에러를 문제없이 처리할 수 있다.

비동기 처리에서 발생한 에러는 then 메서드의 두번째 콜백 함수로 처리할 수 있다.

```jsx {3}
promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
);
```

또한 catch 메서드를 사용해 처리할 수도 있다.

```jsx {3}
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err));
```

catch 메서드를 호출하면 내부적으로 then을 호출하며 다음과 같이 처리된다.

```jsx {3}
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .then(undefined, (err) => console.error(err));
```

그러나 then 메서드의 두번째 콜백 함수로 에러 처리를 하게 되면 첫번째 콜백 함수에서 발생한 에러를 캐치하지 못한다는 문제가 있다.
아래 예시에서 console.xxx라는 함수가 존재하지 않으므로 에러가 발생해야 하지만 두번째 콜백함수는 이를 캐치하지 못한다.

```jsx
promiseGet(rightUrl).then(
  (res) => console.xxx(res),
  (err) => console.error(err)
);
```

catch 메서드를 모든 then 메서드 호출 이후에 호출하면 <Wavy>비동기 처리에서 발생한 에러 뿐 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.</Wavy>

```jsx {3}
promiseGet(rightUrl)
  .then((res) => console.xxx(res))
  .catch((err) => console.error(err)); //TypeError: console.xxx is not function
```

따라서 <Wavy>에러 처리는 then 메서드 대신 catch 메서드에서 하는 것을 권장한다.</Wavy>

## 프로미스 체이닝

위에서 살펴본 콜백 헬 예제를 프로미스를 사용해 다시 구현해보자.

```jsx
get('/step1')
  .then((a) => get(`/step2/${a}`))
  .then((b) => get(`/step3/${b}`))
  .then((c) => get(`/step4/${c}`))
  .then((d) => console.log(d))
  .catch((err) => console.error(err));
```

위 예제에서는 then → then → then → then → catch 순서로 후속 처리 메서드를 호출한다. then, catch, finally 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다. 이를 **프로미스 체이닝**(promise chaining)이라 한다.

위 예제에서 후속 처리 메서드는 다음과 같이 인수를 전달받으면서 호출된다.

| 후속 처리 메서드 | 콜백 함수의 인수                                                                                        | 후속 처리 메서드의 반환값                             |
| ---------------- | ------------------------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| then             | get 함수가 반환한 프로미스가 resolve한 값                                                               | 콜백 함수가 반환한 프로미스                           |
| then             | 첫번째 then 메서드가 반환한 프로미스가 resolve 한 값                                                    | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| then             | 두번째 then 메서드가 반환한 프로미스가 resolve 한 값                                                    | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| then             | 세번째 then 메서드가 반환한 프로미스가 resolve 한 값                                                    | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| catch            | get 함수나 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값 (에러가 발생하지 않으면 호출되지 않음) | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |

이처럼 then, catch, finally 메서드는 콜백 함수가 반환한 프로미스를 반환하며, 프로미스가 아닌 값을 반환하더라도 그 값을 resolve 또는 reject하여 프로미스를 생성해 반환한다.

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 콜백 헬이 발생하지 않지만, 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.
이 문제는 ES8에서 도입된 async/await를 통해 해결할 수 있다. async/await를 사용하면 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

## 프로미스의 정적 메서드

Promise는 5가지 정적 메서드를 제공한다.

### Promise.resolve/Promise.reject

Promise.resolve 메서드는 인수로 전달받은 값을 resolve 하는 프로미스를 생성한다.

```jsx
const resolvedPromse = Promise.resolve([1, 2, 3]);
// const resolvedPromse = new Promise(resolve => resolve([1, 2, 3]);
resolvedPromise.then(console.log); //[1, 2, 3]
```

Promise.reject 메서드는 인수로 전달받은 값을 reject 하는 프로미스를 생성한다.

```jsx
const rejectedPromise = Promise.reject(new Error('Error!'));
// const rejectedPromise = new Promise((_, reject) => reject(new Error('Error!')));
rejectedPromise.catch(console.log); //Error: Error!
```

### Promise.all

Promise.all 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다. 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고, 전달받은 프로미스가 모두 fulfilled(성공) 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3]
  .catch(console.error);
```

Promise.all 메서드가 종료하는 데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 시간보다 조금 더 길다. 위 예제의 경우 3초보다 조금 더 소요된다.

모든 프로미스가 fulfilled 상태가 되면 resolve된 처리 결과를 저장해 새로운 프로미스를 반환하는데, 앞선 프로미스가 나중에 fulfilled 상태가 되어도 Promise.all 메서드는 첫 프로미스 처리 결과부터 차례대로 배열에 저장한다. 즉, <Wavy>처리 순서가 보장된다.</Wavy>

Promise.all 메서드는 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스를 기다리지 않고 즉시 종료한다. rejected 상태가 되는 프로미스가 존재할 경우 가장 먼저 rejected 되는 프로미스가 reject 한 에러가 catch 메서드로 전달된다.

Promise.all 메서드는 인수로 전달받은 이터러블의 요소가 프로미스가 아닌 경우 Promise.resolve 메서드를 통해 프로미스로 래핑한다.

```jsx
Promise.all([
  1, //Promise.resolve(1)
  2, //Promise.resolve(2)
  3, //Promise.resolve(3)
])
  .then(console.log) //[1, 2, 3]
  .catch(console.log);
```

### Promise.race

Promise.race 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다. 모든 프로미스의 fulfilled 상태를 기다리는 것이 아닌 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve 하는 새로운 프로미스를 반환한다.

```jsx
Promise.race([
	new Promise(resolve => setTimeout(() => resolve(1), 3000)),
	new Promise(resolve => setTimeout(() => resolve(2), 2000)),
	new Promise(resolve => setTimeout(() => resolve(3), 1000));
])
	.then(console.log) //3
	.catch(console.log);
```

인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

### Promise.allSettled

Promise.allSettled 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 전달받은 프로미스가 모두 settled(fulfilled 또는 rejected) 상태가 되면 처리 결과를 배열로 반환한다.

```jsx
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error('Error!')), 1000)
  ),
]).then(console.log);

/*
[
	{status: "fulfilled", value: 1},
	{status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

## 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위 예제는 2 → 3 → 1 순서로 출력된다.

프로미스의 후속 처리 메서드의 콜백함수는 태스크 큐가 아닌 **마이크로태스크 큐**(microtask queue)에 저장되기 때문이다.

마이크로태스크 큐는 태스크 큐보다 우선순위가 높다. 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행하고, 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

<br />
**참고자료**

모던 자바스크립트 Deep Dive 45장 프로미스 참조
